"""
Phase 3 — Embedding and Storage
Orchestrates the full ingestion pipeline:
  1. scrape_priority_sections()
  2. chunk_by_headings()
  3. enrich_chunks()
  4. embed_chunks()
  5. store_in_supabase()
"""

import asyncio
import logging
import os

import google.generativeai as genai
from dotenv import load_dotenv
from supabase import create_client, Client

from scraper import scrape_priority_sections
from chunker import chunk_by_headings
from enricher import enrich_chunks

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ── Clients ──────────────────────────────────────────────────────────────────
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

SUPABASE_URL: str = os.environ["SUPABASE_URL"]
SUPABASE_KEY: str = os.environ["SUPABASE_KEY"]

EMBEDDING_MODEL = "models/gemini-embedding-001"
EMBEDDING_DIM = 768


# ── Embedding ─────────────────────────────────────────────────────────────────
def embed_text(text: str) -> list[float]:
    """Embed a single string using gemini-embedding-001. Returns a 768-dim vector."""
    result = genai.embed_content(
        model=EMBEDDING_MODEL,
        content=text,
        task_type="retrieval_document",
        output_dimensionality=768,
    )
    vector = result["embedding"]
    assert len(vector) == EMBEDDING_DIM, f"Expected {EMBEDDING_DIM} dims, got {len(vector)}"
    return vector


def embed_chunks(chunks: list[dict]) -> list[dict]:
    """
    Embed the embedding_text field of each chunk.
    Adds an 'embedding' key (list[float], 768 dims) to each chunk dict.
    Respects the free tier rate limit of ~10 requests/minute with a delay.
    """
    embedded = []
    for i, chunk in enumerate(chunks):
        try:
            vector = embed_text(chunk["embedding_text"])
            embedded.append({**chunk, "embedding": vector})
            if (i + 1) % 10 == 0:
                logger.info(f"Embedded {i + 1}/{len(chunks)} chunks...")
        except Exception as e:
            logger.error(f"Embedding failed for chunk {i} (heading='{chunk.get('heading')}'): {e}")
            # Skip this chunk rather than crashing the whole pipeline

        # Respect free tier rate limit: ~10 requests/minute = 1 per 6 seconds
        # Add a small sleep between every call to avoid 429s
        import time
        time.sleep(6)

    logger.info(f"Embedding complete. {len(embedded)}/{len(chunks)} chunks embedded.")
    return embedded


# ── Storage ───────────────────────────────────────────────────────────────────
def store_in_supabase(chunks: list[dict]) -> None:
    """
    Insert all embedded chunks into the Supabase 'chunks' table.
    Uses the service role key to bypass Row Level Security during ingestion.
    fts_vector is auto-generated by Postgres — do NOT insert it.
    """
    # Use service role key for ingestion to bypass RLS
    # Fall back to anon key if service key not set
    service_key = os.environ.get("SUPABASE_SERVICE_KEY") or os.environ["SUPABASE_KEY"]
    supabase: Client = create_client(SUPABASE_URL, service_key)

    rows = [
        {
            "content": chunk["content"],
            "description": chunk.get("description", ""),
            "heading": chunk.get("heading", ""),
            "url": chunk.get("url", ""),
            "embedding": chunk["embedding"],
        }
        for chunk in chunks
    ]

    # Insert in batches of 50 to stay within Supabase request limits
    batch_size = 50
    total_inserted = 0
    for i in range(0, len(rows), batch_size):
        batch = rows[i : i + batch_size]
        try:
            supabase.table("chunks").insert(batch).execute()
            total_inserted += len(batch)
            logger.info(f"Inserted batch {i // batch_size + 1}: {total_inserted}/{len(rows)} rows")
        except Exception as e:
            logger.error(f"Supabase insert failed for batch starting at {i}: {e}")

    logger.info(f"Storage complete. {total_inserted} rows inserted into Supabase.")


# ── Pipeline ──────────────────────────────────────────────────────────────────
async def run_ingest() -> None:
    logger.info("=== Starting ingestion pipeline ===")

    # Step 1 — Scrape
    logger.info("Step 1: Scraping priority sections...")
    pages = await scrape_priority_sections()
    logger.info(f"  → {len(pages)} pages scraped")

    # Step 2 — Chunk
    logger.info("Step 2: Chunking pages by headings...")
    raw_chunks = chunk_by_headings(pages)
    logger.info(f"  → {len(raw_chunks)} raw chunks produced")

    # Step 3 — Enrich
    logger.info("Step 3: Enriching chunks with LLM descriptions...")
    enriched_chunks = await enrich_chunks(raw_chunks)
    logger.info(f"  → {len(enriched_chunks)} chunks enriched")

    # Step 4 — Embed
    logger.info("Step 4: Embedding chunks...")
    embedded_chunks = embed_chunks(enriched_chunks)
    logger.info(f"  → {len(embedded_chunks)} chunks embedded")

    # Step 5 — Store
    logger.info("Step 5: Storing chunks in Supabase...")
    store_in_supabase(embedded_chunks)

    logger.info("=== Ingestion pipeline complete ===")


if __name__ == "__main__":
    asyncio.run(run_ingest())
